<?xml version="1.0" encoding="utf-8"?><Database Name="Operaciones_CRUD_Empleados" Class="DB_CRUD_EmployeesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LUISMG\SQLMG;Initial Catalog=Operaciones_CRUD_Empleados;User ID=sa" SettingsObjectName="CRUD_Operations.Data.Properties.Settings" SettingsPropertyName="Operaciones_CRUD_EmpleadosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="[Id Employee]" Member="Id_Employee" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Date Of Hire]" Member="Date_Of_Hire" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[Photo Employee]" Member="Photo_Employee" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Employee Name]" Member="Employee_Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Employee Family Name]" Member="Employee_Family_Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Date Of Birth]" Member="Date_Of_Birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Id User]" Member="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Employee" Member="User" ThisKey="Id_User" OtherKey="Id_User" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="[Id User]" Member="Id_User" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[User Password]" Member="User_Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="User_Employee" Member="Employees" ThisKey="Id_User" OtherKey="Id_User" Type="Employee" />
    </Type>
  </Table>
</Database>